--DROP OBJETOS Y TABLAS
--DROP TABLAS
DROP TABLE INCIDENTE;
DROP TABLE GRAVEDAD;
DROP TABLE TAREA;
DROP TABLE SPRINT;
DROP TABLE BACKLOG;
DROP TABLE PROYECTO;
DROP TABLE USUARIO;
--DROP SECUENCIAS
DROP SEQUENCE USER_SERIAL;
DROP SEQUENCE PROJECT_SERIAL;
DROP SEQUENCE BACKLOG_SERIAL;
DROP SEQUENCE SPRINT_SERIAL;
DROP SEQUENCE TAREA_SERIAL;
DROP SEQUENCE INCIDENTE_SERIAL;

CREATE SEQUENCE USER_SERIAL START 1;
CREATE SEQUENCE PROJECT_SERIAL START 1;
CREATE SEQUENCE BACKLOG_SERIAL START 1;
CREATE SEQUENCE SPRINT_SERIAL START 1;
CREATE SEQUENCE TAREA_SERIAL START 1;
CREATE SEQUENCE INCIDENTE_SERIAL START 1;


CREATE TABLE USUARIO(
    ID BIGINT PRIMARY KEY,
    NOMBRE  TEXT,
    USERNAME TEXT,
    PASSW TEXT,
    CARGO TEXT
);

CREATE TABLE PROYECTO(
    ID BIGINT PRIMARY KEY,
    NOMBRE TEXT,
    DESCIPCION TEXT,
    ID_PROPIETARIO BIGINT,
    SCRUM_MASTER BIGINT,
    FOREIGN KEY (ID_PROPIETARIO) REFERENCES USUARIO (ID),
    FOREIGN KEY (SCRUM_MASTER) REFERENCES USUARIO (ID)
);

CREATE TABLE BACKLOG(
    ID BIGINT PRIMARY KEY,
    ID_PROYECTO BIGINT,
    DESCRIPCION TEXT,
    FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID)
);

CREATE TABLE SPRINT(
    ID BIGINT PRIMARY KEY,
    FECHA_INICIO TIMESTAMP,
    FECHA_FIN TIMESTAMP
);

CREATE TABLE TAREA(
    ID BIGINT PRIMARY KEY,
    NOMBRE TEXT,
    DESCRIPCION TEXT,
    ASIGNADO BIGINT,
    FECHA_INICIO TIMESTAMP,
    FECHA_FIN TIMESTAMP,
    ID_SPRINT BIGINT,
    FOREIGN KEY (ASIGNADO) REFERENCES USUARIO (ID),
    FOREIGN KEY (ID_SPRINT) REFERENCES SPRINT (ID)
);

CREATE TABLE GRAVEDAD(
    ID BIGINT PRIMARY KEY,
    DESCRIPCION TEXT
);

CREATE TABLE INCIDENTE(
    ID BIGINT PRIMARY KEY,
    DESCIPCION TEXT,
    FECHA_INICIO TIMESTAMP,
    FECHA_FIN TIMESTAMP,
    ID_GRAVEDAD BIGINT,
    FOREIGN KEY (ID_GRAVEDAD) REFERENCES GRAVEDAD (ID)
);
